### ISSUE TITLE
Fail to load on dedicated server

### ISSUE THREAD

**Issue by 4li77l3n00b** [XiaoHuNao/CreateHeatJS#3]
[crash-2024-09-06_00.11.17-fml.txt](https://github.com/user-attachments/files/16904170/crash-2024-09-06_00.11.17-fml.txt)

**Comment by 4li77l3n00b** [comment]
Seems to be caused by EntityJS, closing now.

**Comment by XiaoHuNao** [comment]
以修复请更新0.0.3
