### ISSUE TITLE
Crashed when filling Basin with water

### ISSUE THREAD

**Issue by liuseniubi** [XiaoHuNao/CreateHeatJS#4]
As the title said

往工作盆中放水导致游戏崩溃（上面放个搅拌器 / 辊压机）
稳定复现，试了三次都是这样（（（

这里是[崩溃日志](https://pastebin.com/GDZj5G7B)

**Comment by XiaoHuNao** [comment]
以修复请更新0.0.3

**Comment by liuseniubi** [comment]
更新 003 后依旧崩溃，甚至这次没有写脚本（
https://pastebin.com/WrLVrPYQ
